Update Readme
netlify/templates pull request #304
Opened 2023-01-04 23:39 UTC by taty2010

adding that this repo is now archived

**- Summary**

**- Test plan**

**- Description for the changelog**

2023-01-04 23:42 UTC, taty2010 commented
@MarcL and @stephan1echung I ended up only needing to make a small change to the Readme since the Redirects notice was already added. If you don't think this is enough let me know.

2023-01-05 00:00 UTC, stephan1echung requested changes
Left a super smol comment to update copy ever so slightly!

2023-01-05 00:00 UTC, stephan1echung commented on README.md
> +:warning: the [templates.netlify.com](https://templates.netlify.com/) repo is now archived and currently being redirected to relevant GitHub repos, [jamstack.org/](https://jamstack.org/), or [www.net
I'd change this ever so slightly to `The [templates.netlify.com](https://templates.netlify.com/) repo is now archived, and the site is currently being redirected to relevant...`

2023-01-05 18:08 UTC, stephan1echung approved these changes
LGTM :shipit:

2023-01-05 18:10 UTC, merged